export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const SAVE_USER_REQUEST = "SAVE_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const ROADMAP_SKILLS_REQUEST = "ROADMAP_SKILLS_REQUEST";
