export const FETCH_SKILL_REQUEST = "FETCH_SKILL_REQUEST";
export const UPDATE_SKILL_REQUEST = "UPDATE_SKILL_REQUEST";
export const SKILL_SUCCESS = "SKILL_SUCCESS";
export const SKILL_FAILURE = "SKILL_FAILURE";
